<?php
namespace Demo\Block\Block;

class Weather extends \Magento\Framework\View\Element\Template
{
    protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}